### ISSUE TITLE
SyntaxError: Unexpected String error when trying to install to server with command line

### ISSUE THREAD

**Issue by XCraftMC23** [holy-unblocker/website-aio#1]
Here's the full error:
```
SyntaxError: Unexpected string
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by e9x** [comment]
What command(s) did you run to see this error?

**Comment by e9x** [comment]
Closing for inactivity.
