### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by HissingSoldier** [holy-unblocker/website-aio#16]
Hello, I am trying to install this onto an AWS EC2 instance, and it was going perfectly fine until I got this issue once I had attempted to start it up.

Here is the output after I started the project.
```
> website-aio@1.0.0 start
> node scripts/start.js

file:///root/workspace/website-aio/scripts/start.js:57
const rhPort = await findPort();
               ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
I am running **Ubuntu 22.04**

I don't think that I missed anything but if I did, please tell me, thanks for your time!

**Comment by HissingSoldier** [comment]
I found the fix, all I needed to do was update the node version to 14.

**Comment by TurtleMeds** [comment]
I have the same issue but updating node doesn't seem to help.
